/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import ejercicioextra1.ListaDeTareas;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author agus_
 */
public class ListaView extends javax.swing.JInternalFrame {
    
    private DefaultListModel modelo1 = new DefaultListModel();
    private DefaultListModel modelo2 = new DefaultListModel();

    /**
     * Creates new form ListaView
     */
    public ListaView() {
        initComponents();
        jlListaCompletas.setModel(modelo2);
        jlListaIncompletas.setModel(modelo1);
        mostrarLista();
        mostrarListaCompletas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlListaIncompletas = new javax.swing.JList<>();
        jbCompleta = new javax.swing.JButton();
        jbIncompleta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlListaCompletas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE TAREAS");

        jScrollPane1.setViewportView(jlListaIncompletas);

        jbCompleta.setText("Completa");
        jbCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCompletaActionPerformed(evt);
            }
        });

        jbIncompleta.setText("Incompleta");
        jbIncompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncompletaActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jlListaCompletas);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tareas incompletas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tareas completas");

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jbSalir, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jbCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbIncompleta)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbIncompleta)
                    .addComponent(jbCompleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCompletaActionPerformed
        // TODO add your handling code here:
        List<String> seleccion = jlListaIncompletas.getSelectedValuesList();
        
        ListaDeTareas.listaDeTareasCompletas.addAll(seleccion);
        
        ListaDeTareas.listaDeTareas.removeAll(seleccion);
        modelo1.removeAllElements();
        modelo2.removeAllElements();
        mostrarLista();
        mostrarListaCompletas();
    }//GEN-LAST:event_jbCompletaActionPerformed

    private void jbIncompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncompletaActionPerformed
        // TODO add your handling code here:
        List<String> seleccion = jlListaCompletas.getSelectedValuesList();
        
        ListaDeTareas.listaDeTareas.addAll(seleccion);
        
        ListaDeTareas.listaDeTareasCompletas.removeAll(seleccion);
        modelo1.removeAllElements();
        modelo2.removeAllElements();
        mostrarLista();
        mostrarListaCompletas();
    }//GEN-LAST:event_jbIncompletaActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbCompleta;
    private javax.swing.JButton jbIncompleta;
    private javax.swing.JButton jbSalir;
    private javax.swing.JList<String> jlListaCompletas;
    private javax.swing.JList<String> jlListaIncompletas;
    // End of variables declaration//GEN-END:variables

    private void mostrarLista(){
        for (int i = 0; i < ListaDeTareas.listaDeTareas.size(); i++) {
            modelo1.addElement(ListaDeTareas.listaDeTareas.get(i));
        }
    }
    
    private void mostrarListaCompletas(){
        for (int i = 0; i < ListaDeTareas.listaDeTareasCompletas.size(); i++) {
            modelo2.addElement(ListaDeTareas.listaDeTareasCompletas.get(i));
        }
    }
}
